improve image creation/hanfdling in bin/myarm

diff --git a/bin/myarm b/bin/myarm
--- a/bin/myarm
+++ b/bin/myarm
@@ -38,18 +38,18 @@ report_status()
 
 function make_sure_img_exist()
 {
-  [[ -f /dev/shm/$1-${IMAGE##*/} ]] || {
-    echo "Disk image '$1' missing - creating"
-    qemu-img create /dev/shm/$1-${IMAGE##*/} $2
-    mkswap /dev/shm/$1-${IMAGE##*/}
-    echo "Disk image '$1' created"
+  [[ -f $3 ]] || {
+    echo "Disk image '$3' missing - creating"
+    qemu-img create $3 $2
+    mkfs -t $1 $3
+    echo "Disk image '$3' created"
   }
 }
 
 function start_image()
 {
-  make_sure_img_exist swap 2G
-  make_sure_img_exist data 8G
+  make_sure_img_exist swap 2G /dev/shm/swap-${IMAGE##*/}
+  make_sure_img_exist ext4 8G data-${IMAGE##*/}
   echo "Starting image"
   qemu-system-arm \
     -cpu $CPU \
@@ -59,7 +59,7 @@ function start_image()
     -append "root=/dev/sda2 panic=1" \
     -hda $IMAGE \
     -hdb /dev/shm/swap-${IMAGE##*/} \
-    -hdc /dev/shm/data-${IMAGE##*/} \
+    -hdc data-${IMAGE##*/} \
     -redir tcp:$PORT::22 \
     -ctrl-grab \
     -no-reboot \
